---
#############################################################################
#                       Confidentiality Information                         #
#                                                                           #
# This module is the confidential and proprietary information of            #
# DBSentry Corp.; it is not to be copied, reproduced, or transmitted in any #
# form, by any means, in whole or in part, nor is it to be used for any     #
# purpose other than that for which it is expressly provided without the    #
# written permission of DBSentry Corp.                                      #
#                                                                           #
# Copyright (c) 2020-2021 DBSentry Corp.  All Rights Reserved.              #
#                                                                           #
#############################################################################
## Creates/Deletes Terraform role for target environment
#############################################################################
- name: Terraform Role in target environment. Target State - {{ tf_target_state }}
  when: true
  terraform:
    project_path: "{{ role_path }}/files/{{ aws_account_name }}"
    state: "{{ tf_target_state }}"
    force_init: true
    lock: yes
    backend_config:
      region: "{{ aws_default_region }}"
      bucket: "{{ tf_bucket }}"
      key: "tf-role.tfstate"
      dynamodb_table: "{{ tf_dynamodb_table }}"
      encrypt: "true"
    variables:
      all_vars: "{{ all_vars | to_json }}"
      group_vars: "{{ group_vars | to_json }}"
  environment: 
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_DEFAULT_REGION: "{{ aws_default_region }}"