#########################################################################################
# iac-deploy.yml
#   Playbook to deploy IaC code using Terraform. 
#########################################################################################
- name: Deploy IaC code
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aws_account_name: "{{ group_names[0] }}"
    aws_account_name_list: "{{ groups.keys()  | reject('match', 'all') | reject('match', 'ungrouped') }}"
    tf_target_state: "planned"
    tf_blast_radius_all: "all"

  pre_tasks:
  - name: Read Secret Variable
    include_vars:
      file: aws-deploy-secrets.yml
      name: aws_secret_vars
    tags:
      - always
  - name: Set Variables
    set_fact:
      aws_access_key_id: "{{ aws_secret_vars[all_vars.org_account_name + '_aws_access_key_id'] }}"
      aws_secret_access_key: "{{ aws_secret_vars[all_vars.org_account_name + '_aws_secret_access_key'] }}"
      aws_default_region: "{{ aws_secret_vars[all_vars.org_account_name + '_aws_default_region'] }}"
      tf_bucket: "{{ all_vars.tfstate_namespace + '-' + aws_account_name + '-' + all_vars.tfstate_name + '-state'}}"
      tf_dynamodb_table: "{{ all_vars.tfstate_namespace + '-' + aws_account_name + '-' + all_vars.tfstate_name + '-state-lock'}}"
      tf_blast_radius: "{{ ansible_run_tags | sort }}"
    tags:
      - always

  roles:
   - { role: iac-aws, secrets: "{{ aws_secret_vars }}", tags: ["always"]  }

