- name: Check if folder exists
  stat:
    path: "{{ tf_directory }}/{{ tf_stack }}"
  register: tf_folder_data

- name: Report a missing folder
  debug:
    msg: "Ignoring missing folder {{ tf_stack }}"
  when: not tf_folder_data.stat.exists

- block:
    - name: AWS. Target State - {{ tf_target_state }}
      terraform:
        project_path: "{{ tf_directory }}/{{ tf_stack }}"
        state: "{{ tf_target_state }}"
        force_init: true
        lock: yes
        backend_config:
          region: "{{ aws_default_region }}"
          bucket: "{{ tf_bucket }}"
          key: "{{ tf_stack }}.tfstate"
          dynamodb_table: "{{ tf_dynamodb_table }}"
          role_arn: "arn:aws:iam::{{ group_vars.account_id }}:role/{{ all_vars.tfrole }}"
          encrypt: "true"
        variables:
          all_vars: "{{ all_vars | to_json }}"
          group_vars: "{{ group_vars | to_json }}"
      environment: 
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_default_region }}"
      register: output
      when: tf_target_state in ["present","absent"]

    - name: AWS. Target State - {{ tf_target_state }}
      terraform:
        project_path: "{{ tf_directory }}/{{ tf_stack }}"
        state: "{{ tf_target_state }}"
        force_init: true
        lock: yes
        plan_file: "{{ tf_directory }}/{{ tf_stack }}/{{ tf_stack }}.tfplan"
        backend_config:
          region: "{{ aws_default_region }}"
          bucket: "{{ tf_bucket }}"
          key: "{{ tf_stack }}.tfstate"
          dynamodb_table: "{{ tf_dynamodb_table }}"
          role_arn: "arn:aws:iam::{{ group_vars.account_id }}:role/{{ all_vars.tfrole }}"
          encrypt: "true"
        variables:
          all_vars: "{{ all_vars | to_json }}"
          group_vars: "{{ group_vars | to_json }}"
      environment: 
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_default_region }}"
      register: output
      when: tf_target_state in ["planned"]

    - debug:
        msg: "{{ output }}"
  when: tf_folder_data.stat.exists